name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # リポジトリの内容への書き込みを許可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.5"
      - name: Install dependencies
        run: bundle install
      - name: Build site with Jekyll
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
